% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Feb-2021 09:53:14
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
saveVarsMat = load('MatrixC.mat');

C = saveVarsMat.C; % <32x32 double> too many elements

clear saveVarsMat;
